services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: c43
      POSTGRES_PASSWORD: c43
      POSTGRES_DB: snfs
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql


  web:
    build: .
    container_name: flask_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development

volumes:
  pgdata:
