name: Backend Checks

on:
  pull_request:
    branches: ['main']
    paths: 
      - 'backend/**/*.py'

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3