name: Frontend Checks

on:
  pull_request:
    branches: ['main']
    paths:
      - 'frontend/**'

jobs:
  frontend-checks:
    name: Frontend Build, Lint, and Format
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Run Build
        run: npm run build

      - name: Run Lint
        run: npm run lint

      - name: Run Format Check
        run: npm run prettier